name: softball
favicon: null
layout_spectrum: 0.278720305301249
typography_spectrum: 0.13843176560476422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5677182876970619
  lightness: 0.6800321240443736
  saturation: 0.22210423392243683
  rhythmicContrast: 0.470788047183305
purpose: []
